# @package _group_
type: gunnar_ode
h_size: 32
ode_hidden_size: 30
num_layers: 1
ode_solver: dopri5
ode_num_layers: 1
theta: 1.0
mu: 0.0
sigma: 0.5
inter: 'zero' # zero, cubic, gp
dt: 5e-2 # 跑得太慢了的话把这个调大，但是不要超过0.1
rtol: 0.001
atol: 0.001
method: euler
adaptive: no