type: southeast32
input_size: 3
observation_size: 2
dataset_window: 10
data_path: data/south_con/thickener_1.npy # it can also be set as thickener_2.npy
io: 3-2
history_length: 30
forward_length: 60
target_names: ['UC', 'Pressure']
smooth_alpha: 0.3