type: thickener_rake
input_size: 5
observation_size: 4
dataset_window: 5
train_path: data/thickener_rake/thickener_rake_train.csv
val_path: data/thickener_rake/thickener_rake_val.csv
test_path: data/thickener_rake/thickener_rake_test.csv
target_names: ['rake_1', 'rake_2', 'rake_3', 'rake_4']
history_length: 120
forward_length: 120