type: thickener_sim
input_size: 2
observation_size: 4
dataset_window: 5
train_path: data/thickener_sim/thickener_simulation_18000_train.csv
val_path: data/thickener_sim/thickener_simulation_6000_val.csv
test_path: data/thickener_sim/thickener_simulation_6000_test.csv
target_names: ['y_h', 'y_c', 'c_fi', 'c_ci']
history_length: 60
forward_length: 180